version: "2"
services:
  dipper-sync:
    container_name: dipper-sync
    image: ixofoundation/ixo-dippersync:latest
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGODB_BIG_DIPPER_URI=mongodb://dipper-sync-db:27017/big-dipper-DB
    restart: always
    ports:
      - "80:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
